version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/code
  php:
    build: .
    volumes:
      - ./:/code